version: '3'
services:
  screeps:
    container_name: screeps
    image: elbarae/screeps-launcher-arm
    volumes:
      - ./config.yml:/screeps/config.yml
      - screeps-data:/screeps
    ports:
      - 21025:21025/tcp
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
    restart: unless-stopped

  mongo:
    container_name: screeps-mongo
    image: mongo
    command: --quiet
    volumes:
      - ./docker-volumes/mongo-data:/data/db
    restart: unless-stopped

  redis:
    container_name: screeps-redis
    image: redis
    volumes:
      - ./docker-volumes/redis-data:/data
    restart: unless-stopped

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #     - 443:443

volumes:
  screeps-data:
